depstep
kysect/Efilir pull request #3
Opened 2020-03-23 19:28 UTC by moskovetsstep1

2020-03-23 20:03 UTC, FrediKats requested changes

2020-03-23 20:03 UTC, FrediKats commented on GenericLife.Core/Environment/GameArea.cs
> +                        default: Console.WriteLine($"An unexpected value"); break;
Кажется, нужно убрать.

2020-03-23 20:03 UTC, FrediKats commented on GenericLife.Core/Tools/DataSaver.cs
> +                return JsonConvert.DeserializeObject<int[,]>(File.ReadAllText(FieldFileName));
Лучше обернуть в try/catch

2020-03-23 20:03 UTC, FrediKats commented on GenericLife.Core/Environment/GameArea.cs
> +        public void CleanField(int[,] cells)
Clean как-то не вяжется с тем, что внутри генерируется что-то. Оно же читстиь должно, не?

2020-03-23 20:03 UTC, FrediKats commented on GenericLife.Core/Environment/GameArea.cs
> +            for (var i = 0; i < Configuration.FieldSize; i++)
Почему оно по размеру из конфига, а не по размеру того, что с файла считало?

2020-03-23 20:03 UTC, FrediKats commented on GenericLife.Core/Environment/SimulationManger.cs
> +            DeleteAllElements(cells);
Выглядит странно. Почему мы в конструкторе удаляем что-то? Это же конструктор.

2020-03-23 20:03 UTC, InRedikaWB commented on GenericLife/Tools/TestingPolygon.cs
> -            CellField.DeleteAllElements();
Почему бы тут не оставить удаление и не добавить метод для генерации стен? Будет
.DeleteAll()
.GenerateWalls()
.InitCells()

2020-03-23 20:03 UTC, InRedikaWB commented on GenericLife/Tools/TestingPolygon.cs
> +            return DataSaver.LoadField();
Зачем метод, который просто вызвает другой? Почему бы там сразу не вызывать DataSaver.LoadField()?

2020-03-23 21:31 UTC, hrrrrustic commented on GenericLife.Core/Environment/GameArea.cs
> +                        default: Console.WriteLine($"An unexpected value"); break;
Не убрать, а переписать!

2020-04-03 16:10 UTC, FrediKats approved these changes

2020-04-03 16:12 UTC, merged