Refactor: Changed three-dimensional array to linear
kysect/Efilir pull request #7
Opened 2022-01-15 16:26 UTC by Mihinator3000

2022-01-17 19:56 UTC, FrediKats commented
Выглядит неплохо, там ушли немного аллокации.
Было:
![image](https://user-images.githubusercontent.com/22368203/149830083-2cbf44e4-6fb6-428e-88ef-742e794cfee9.png)

Стало:
![image](https://user-images.githubusercontent.com/22368203/149830106-f14356b5-19c5-4352-9a92-9c3f9de89c05.png)


Очень грубая оценка, конечно, но теперь отрисовка занимает меньший процент времени работы. Из интересного ещё заметил, что очень грустно коду становится на 
```csharp
        public void DrawPoints<T>(ICollection<T> cells) where T : IBaseCell
        {
            var pixels = new byte[ArraySize];
            PrintBackgroundWithBlack(pixels);

            foreach (T cell in cells)
                PutCell(pixels, cell);
            
            PrintPixels(pixels);
        }
```

Там каждый раз создаётся новый массив. А потом мы его зануляем. А что если мы не будем его создавать, а будет один раз хранить? Мб поможет. Если интересно, кста, можешь себе скачать dotTrace, тулу от JetBrains, она умеет делать снимки перфа и показывать где аллокации или выполняется долго. Скрины с неё. Может ещё что-то интересное будет. Но мне кажется вот это создание убрать и будет топ.

2022-01-17 19:57 UTC, FrediKats requested changes
В комменте выше отписал предложение по ещё одному изменению в этом же месте.

2022-01-18 00:01 UTC, Mihinator3000 commented
Сделал только 1 создание массива, насколько я могу судить теперь аллокаций стало намного меньше.
Было:
![Screenshot_6](https://user-images.githubusercontent.com/70411602/149849205-cdff062a-8502-4bdb-bd1c-53cb76f87262.png)
Стало:
![Screenshot_7](https://user-images.githubusercontent.com/70411602/149849300-6e7dbfb0-a708-4f70-968e-6219289acd8f.png)

2022-01-18 00:10 UTC, Mihinator3000 commented on Efilir.Client/Tools/PixelDrawer.cs
> -        }
Не очень уверен для чего же была сделана эта функция. Мы тут заполняем четвертый канал формата Bgr32, который по сути не используется. Визуально ничего не изменилось, но если это правда было нужно для чего-то, могу вернуть.

2022-01-18 11:24 UTC, FrediKats approved these changes
Выглядит круто. Спасибо!

2022-01-18 13:27 UTC, Mihinator3000 commented on Efilir.Client/Tools/PixelDrawer.cs
> -        }
@FrediKats, по поводу этого ничего не надо менять? 

Еще у меня прав на мердж нет, мержнешь?

2022-01-19 15:07 UTC, FrediKats commented on Efilir.Client/Tools/PixelDrawer.cs
> -        }
А, ой, не подумал, что нет прав.
А это видимо старое что-то.

2022-01-19 15:07 UTC, merged